### Bank Credit Card Default Prediction :

#### Import Necessary Libraries :

In [11]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#### Read Files :

In [12]:
df = pd.read_csv(r"G:\Imarticus LMS\SVM_Using_Python\BankCreditCard.csv")

#### View all rows and columns :

In [13]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [14]:
df.head()

Customer ID  Credit_Amount  Gender  Academic_Qualification  Marital  \
0            1        20000.0       2                       2        1   
1            2       220000.0       2                       2        2   
2            3        90000.0       2                       2        2   
3            4        50000.0       2                       2        1   
4            5        50000.0       1                       2        1   

   Age_Years  Repayment_Status_Jan  Repayment_Status_Feb  \
0         24                     2                     2   
1         26                     0                     2   
2         34                     0                     0   
3         37                     0                     0   
4         57                     0                     0   

   Repayment_Status_March  Repayment_Status_April  Repayment_Status_May  \
0                       0                       0                     0   
1                       0                       0                     0   
2                       0                       0                     0   
3                       0                       0                     0   
4                       0                       0                     0   

   Repayment_Status_June  Jan_Bill_Amount  Feb_Bill_Amount  March_Bill_Amount  \
0                      0           3933.0           3103.0              689.0   
1                      2           3683.0           1735.0             2682.0   
2                      0          39339.0          14037.0            23559.0   
3                      0          46990.0          48333.0            49292.0   
4                      0           8637.0           5570.0            35835.0   

   April_Bill_Amount  May_Bill_Amount  June_Bill_Amount  Previous_Payment_Jan  \
0                0.0              0.0               0.0                   0.0   
1             3272.0           3455.0            3261.0                   0.0   
2            24332.0          14848.0           15548.0                1619.0   
3            29324.0          28858.0           28547.0                3000.0   
4            20940.0          18146.0           18131.0                3000.0   

   Previous_Payment_Feb  Previous_Payment_March  Previous_Payment_April  \
0                 679.0                     0.0                     0.0   
1                2000.0                  1000.0                  1000.0   
2                2500.0                  1000.0                  1000.0   
3                2029.0                  1200.0                  1100.0   
4               36672.0                 10000.0                  9000.0   

   Previous_Payment_May  Previous_Payment_June  Default_Payment  
0                   0.0                    0.0                1  
1                   0.0                 2000.0                1  
2                1000.0                 5000.0                0  
3                1069.0                 1000.0                0  
4                 689.0                  679.0                0

#### Display Column Names :


In [15]:
df.columns

Index(['Customer ID', 'Credit_Amount', 'Gender', 'Academic_Qualification',
       'Marital', 'Age_Years', 'Repayment_Status_Jan', 'Repayment_Status_Feb',
       'Repayment_Status_March', 'Repayment_Status_April',
       'Repayment_Status_May', 'Repayment_Status_June', 'Jan_Bill_Amount',
       'Feb_Bill_Amount', 'March_Bill_Amount', 'April_Bill_Amount',
       'May_Bill_Amount', 'June_Bill_Amount', 'Previous_Payment_Jan',
       'Previous_Payment_Feb', 'Previous_Payment_March',
       'Previous_Payment_April', 'Previous_Payment_May',
       'Previous_Payment_June', 'Default_Payment'],
      dtype='object')

####  Get the number of Rows and Columns :


In [16]:
df.shape

(30000, 25)

#### Check for any misssing null values in the data :


In [17]:
df.isna().sum()

Customer ID               0
Credit_Amount             0
Gender                    0
Academic_Qualification    0
Marital                   0
Age_Years                 0
Repayment_Status_Jan      0
Repayment_Status_Feb      0
Repayment_Status_March    0
Repayment_Status_April    0
Repayment_Status_May      0
Repayment_Status_June     0
Jan_Bill_Amount           0
Feb_Bill_Amount           0
March_Bill_Amount         0
April_Bill_Amount         0
May_Bill_Amount           0
June_Bill_Amount          0
Previous_Payment_Jan      0
Previous_Payment_Feb      0
Previous_Payment_March    0
Previous_Payment_April    0
Previous_Payment_May      0
Previous_Payment_June     0
Default_Payment           0
dtype: int64

##### Get Datatypes :

In [18]:
df.dtypes

Customer ID                 int64
Credit_Amount             float64
Gender                      int64
Academic_Qualification      int64
Marital                     int64
Age_Years                   int64
Repayment_Status_Jan        int64
Repayment_Status_Feb        int64
Repayment_Status_March      int64
Repayment_Status_April      int64
Repayment_Status_May        int64
Repayment_Status_June       int64
Jan_Bill_Amount           float64
Feb_Bill_Amount           float64
March_Bill_Amount         float64
April_Bill_Amount         float64
May_Bill_Amount           float64
June_Bill_Amount          float64
Previous_Payment_Jan      float64
Previous_Payment_Feb      float64
Previous_Payment_March    float64
Previous_Payment_April    float64
Previous_Payment_May      float64
Previous_Payment_June     float64
Default_Payment             int64
dtype: object

##### Drop some Columns which are of no use :

In [19]:
df = df.drop('Customer ID' , axis = 1)


In [22]:
df.shape

(30000, 24)

#### Split data into Train and Test :

In [23]:
x= df.iloc[:, 1:24].values  
y= df.iloc[:, -1].values  
  

In [25]:
x

array([[2.0000e+00, 2.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [2.0000e+00, 2.0000e+00, 2.0000e+00, ..., 0.0000e+00, 2.0000e+03,
        1.0000e+00],
       [2.0000e+00, 2.0000e+00, 2.0000e+00, ..., 1.0000e+03, 5.0000e+03,
        0.0000e+00],
       ...,
       [1.0000e+00, 2.0000e+00, 2.0000e+00, ..., 3.0000e+03, 3.1000e+03,
        1.0000e+00],
       [1.0000e+00, 3.0000e+00, 1.0000e+00, ..., 5.3965e+04, 1.8040e+03,
        1.0000e+00],
       [1.0000e+00, 2.0000e+00, 1.0000e+00, ..., 1.0000e+03, 1.0000e+03,
        1.0000e+00]])

In [26]:
y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [27]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

In [28]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)       

In [29]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC()          #kernel='linear', random_state=0
classifier.fit(x_train, y_train)  

SVC()

#### Predicting the test set result  :


In [30]:
y_pred= classifier.predict(x_test)

#### Creating the Confusion matrix  :


In [31]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [32]:
cm

array([[5868,    0],
       [  19, 1613]], dtype=int64)

In [33]:
cm.diagonal().sum()*100/cm.sum()

99.74666666666667

In [34]:
from sklearn.metrics import  f1_score

In [35]:
print(f1_score(y_test , y_pred))

0.9941448382126349


### Tune Parameters :

#### 1] Regularization(C) :

In [36]:
model_c = SVC(C = 1)

In [37]:
model_c.fit(x_train, y_train)

SVC(C=1)

In [38]:
model_c.score(x_test, y_test)

0.9974666666666666

In [40]:
pred_value = classifier.predict(x_test)

In [42]:
print(f1_score(y_test , y_pred))

0.9941448382126349


#### ..............................................................................................

In [43]:
model_c = SVC(C = 10)

In [44]:
model_c.fit(x_train, y_train)

SVC(C=10)

In [45]:
model_c.score(x_test, y_test)

0.9978666666666667

In [47]:
pred_value = classifier.predict(x_test)

In [48]:
print(f1_score(y_test , y_pred))

0.9941448382126349


#### 2] Gamma :


In [49]:
model_g = SVC(gamma = 10)

In [50]:
model_g.fit(x_train, y_train)

SVC(gamma=10)

In [51]:
model_g.score(x_test, y_test)

0.8370666666666666

In [53]:
pred_value = classifier.predict(x_test)

In [54]:
print(f1_score(y_test , y_pred))

0.9941448382126349


 #### 3] Kernel :

In [55]:
model_linear_kernel_rbf = SVC(kernel = "rbf")

In [56]:
model_linear_kernel_rbf.fit(x_train, y_train)

SVC()

In [57]:
model_linear_kernel_rbf.score(x_test, y_test)

0.9974666666666666

In [59]:
pred_value = classifier.predict(x_test)

In [60]:
print(f1_score(y_test , y_pred))

0.9941448382126349


#### ..........................End ..........................................................................

#### .....................................Thank You .................................................................